# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      cd web
      npm i # runs during prebuild
    command: |
      cd web
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5173
    onOpen: open-preview
